SELECT
    a.ITEM_ID, a.ITEM_NAME, a.RARITY
FROM
    ITEM_INFO AS a
JOIN
    ITEM_TREE AS b
ON
    a.ITEM_ID=b.ITEM_ID
WHERE
    (a.ITEM_ID NOT IN (SELECT PARENT_ITEM_ID FROM ITEM_TREE  WHERE PARENT_ITEM_ID IS NOT NULL)) 
ORDER BY
    a.ITEM_ID DESC
    