SELECT 
    a.CAR_ID,
    a.CAR_TYPE,
    FLOOR(a.DAILY_FEE * 30 * (1 - c.DISCOUNT_RATE / 100)) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR AS a
JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS c 
    ON a.CAR_TYPE = c.CAR_TYPE AND c.DURATION_TYPE = '30일 이상'
WHERE 
    a.CAR_TYPE IN ('세단', 'SUV')
    AND a.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    )
HAVING 
    FEE >= 500000 AND FEE < 2000000
ORDER BY 
    FEE DESC, 
    a.CAR_TYPE ASC, 
    a.CAR_ID DESC;