SELECT
    YEAR(b.SALES_DATE) AS YEAR, MONTH(b.SALES_DATE) AS MONTH, a.GENDER AS GENDER, COUNT(DISTINCT b.USER_ID) AS USERS
FROM
    USER_INFO AS a
JOIN
    ONLINE_SALE AS b
ON
    a.USER_ID=b.USER_ID
WHERE
    GENDER IS NOT NULL
GROUP BY
    YEAR, MONTH, GENDER
ORDER BY
    YEAR, MONTH, GENDER

## 회원수 중복 카운팅 주의