SELECT 
    CASE 
        WHEN (SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End'))
         AND (SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')) THEN 'A'

        WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') THEN 'B'

        WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') THEN 'C'
    END AS GRADE,
    ID, 
    EMAIL
FROM 
    DEVELOPERS

HAVING 
    GRADE IS NOT NULL
ORDER BY 
    GRADE ASC, 
    ID ASC;

## 비트에 포함되있는지 확인하려면 &연산자 활용 &했을때 0이 아니면 해당 비트를 포함하고 있다는걸 내포
