SELECT
    a.AUTHOR_ID, c.AUTHOR_NAME,a.CATEGORY, SUM(b.SALES*a.PRICE) AS TOTAL_SALES
FROM
    BOOK AS a
JOIN
    BOOK_SALES AS b
ON
    a.BOOK_ID=b.BOOK_ID
JOIN
    AUTHOR AS c
ON
    a.AUTHOR_ID=c.AUTHOR_ID
WHERE
    DATE_FORMAT(b.SALES_DATE,"%Y-%m")='2022-01'
GROUP BY
    a.AUTHOR_ID, a.CATEGORY
ORDER BY
    a.AUTHOR_ID, a.CATEGORY DESC